import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.7.1";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { entityType, entityName, entityDescription } = await req.json();
    
    console.log(`Generating image for ${entityType}: ${entityName}`);

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    // Get AI configuration from database
    const { data: aiConfig } = await supabase
      .from('ai_settings')
      .select('setting_value')
      .eq('setting_key', 'ai_api_config')
      .maybeSingle();

    const config = aiConfig?.setting_value as any;

    // Require Google API for image generation
    if (!config?.enabled || config?.provider !== 'google' || !config?.google_api_key) {
      console.error('[generate-seed-images] Google API key not configured for image generation');
      return new Response(
        JSON.stringify({ 
          error: "Google AI API not configured. Image generation requires a Google API key. Please go to Admin → Settings → AI Functions API Key Settings.",
          success: false
        }),
        { status: 503, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Create appropriate prompt based on entity type
    let prompt = "";
    if (entityType === "subject") {
      prompt = `Create a professional, vibrant educational thumbnail image for ${entityName} subject. The image should be modern, engaging, and represent ${entityDescription}. Use bright colors, include relevant symbols or icons related to the subject, and make it suitable for an online learning platform. High quality, 16:9 aspect ratio.`;
    } else if (entityType === "category") {
      prompt = `Create a professional, inspiring banner image for educational category: ${entityName}. ${entityDescription}. The image should be motivational, modern, and appealing to Indian students. Include subtle educational elements. High quality, wide banner format, 16:9 aspect ratio.`;
    } else if (entityType === "course") {
      prompt = `Create an engaging course thumbnail for: ${entityName}. ${entityDescription}. The image should be professional, modern, and appealing to students. Include relevant educational symbols, use vibrant colors, and make it eye-catching for an online course. High quality, 16:9 aspect ratio.`;
    }

    // Generate image using Google Gemini image generation API
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image:generateContent?key=${config.google_api_key}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          contents: [
            {
              parts: [{ text: prompt }],
            },
          ],
          generationConfig: {
            responseModalities: ["TEXT", "IMAGE"],
          },
        }),
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      console.error("Google AI error:", response.status, errorText);
      if (response.status === 429) {
        return new Response(
          JSON.stringify({ error: "Rate limit exceeded. Please try again later.", success: false }),
          { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      if (response.status === 401 || response.status === 403) {
        return new Response(
          JSON.stringify({ error: "Invalid or unauthorized Google API key.", success: false }),
          { status: response.status, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      throw new Error(`Google AI error: ${response.status}`);
    }

    const data = await response.json();
    
    // Extract image from Gemini response
    const parts = data.candidates?.[0]?.content?.parts || [];
    const imagePart = parts.find((part: any) => part.inlineData?.mimeType?.startsWith('image/'));
    
    if (!imagePart?.inlineData?.data) {
      console.error("No image in Google response:", JSON.stringify(data).slice(0, 500));
      throw new Error("No image generated by Google AI");
    }

    const base64Data = imagePart.inlineData.data;
    const mimeType = imagePart.inlineData.mimeType || 'image/png';
    const extension = mimeType.split('/')[1] || 'png';
    
    const imageBuffer = Uint8Array.from(atob(base64Data), (c) => c.charCodeAt(0));

    const fileName = `${entityType}/${entityName.toLowerCase().replace(/\s+/g, "-")}-${Date.now()}.${extension}`;
    
    const { data: uploadData, error: uploadError } = await supabase.storage
      .from("question-images")
      .upload(fileName, imageBuffer, {
        contentType: mimeType,
        upsert: false,
      });

    if (uploadError) {
      console.error("Upload error:", uploadError);
      throw uploadError;
    }

    const { data: urlData } = supabase.storage
      .from("question-images")
      .getPublicUrl(fileName);

    console.log(`Image generated and uploaded: ${urlData.publicUrl}`);

    return new Response(
      JSON.stringify({ 
        success: true, 
        imageUrl: urlData.publicUrl,
        entityName,
        entityType
      }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("Error generating image:", error);
    return new Response(
      JSON.stringify({ 
        error: error instanceof Error ? error.message : "Unknown error",
        success: false
      }),
      { 
        status: 500, 
        headers: { ...corsHeaders, "Content-Type": "application/json" } 
      }
    );
  }
});
