// Shared contract for the pre-generated assistant voice clips (edge-tts MP3s
// under public/assistant-audio/). The manifest listing the actual clips is
// generated by scripts/generate-assistant-audio.py — do not hand-edit it.
export type AssistantClipCategory =
  | "greeting" // opening the assistant mid-lecture
  | "greetingEnd" // opening it automatically when the lecture ends
  | "followUp" // returning from an answer — "anything else?"
  | "thinking" // question received, request sent
  | "stillThinking" // request taking a while, nothing streamed yet
  | "found" // first part of the answer arrived
  | "preparingVisual" // text shown, animated explanation still rendering
  | "outOfScope" // question isn't covered by this subject's material
  | "didntCatch" // speech detected but transcript empty / too short
  | "error" // request failed
  | "stillThere"; // listened a long time without hearing anything

export interface AssistantClip {
  id: string;
  category: AssistantClipCategory;
  /** The exact line spoken — also shown as the assistant's caption. */
  text: string;
  /** Public URL, e.g. "/assistant-audio/greeting/greeting-01.mp3". */
  src: string;
}
