-- Insert 30 sample courses with pricing and details
INSERT INTO courses (name, slug, short_description, description, detailed_description, thumbnail_url, price_inr, original_price_inr, duration_months, rating, student_count, review_count, instructor_name, instructor_bio, instructor_avatar_url, category, is_active, sequence_order, what_you_learn, course_includes) VALUES
-- JEE Courses (10)
('JEE Main Complete Course', 'jee-main-complete', 'Master JEE Main with comprehensive coverage', 'Complete preparation course for JEE Main covering Physics, Chemistry, and Mathematics with expert faculty and regular practice tests.', 'This comprehensive JEE Main preparation course includes detailed video lectures, study materials, and practice questions for all three subjects. Our experienced faculty will guide you through every concept with regular doubt clearing sessions.', '/placeholder.svg', 12000, 15000, 12, 4.8, 5420, 1240, 'Dr. Rajesh Kumar', 'IIT Delhi alumnus with 15 years of teaching experience', '/placeholder.svg', 'JEE', true, 1, '["Advanced problem-solving techniques", "Time management strategies", "Mock test analysis", "Shortcut methods for calculations"]', '["300+ hours of video content", "5000+ practice questions", "50 full-length mock tests", "Personal mentor support"]'),
('JEE Advanced Physics Mastery', 'jee-advanced-physics', 'Deep dive into JEE Advanced Physics', 'Specialized course focusing on advanced physics concepts required for JEE Advanced examination.', 'Master challenging physics concepts with our specialized JEE Advanced Physics course. Includes mechanics, thermodynamics, electromagnetism, and modern physics with advanced problem-solving techniques.', '/placeholder.svg', 8000, 10000, 8, 4.9, 3210, 890, 'Prof. Amit Sharma', 'Former IIT professor, Physics Olympiad trainer', '/placeholder.svg', 'JEE', true, 2, '["Advanced mechanics concepts", "Electromagnetic theory", "Quantum physics basics", "Problem-solving strategies"]', '["200+ hours of content", "3000+ problems", "Weekly live sessions", "Doubt clearing"]'),
('JEE Chemistry Complete', 'jee-chemistry-complete', 'Comprehensive JEE Chemistry preparation', 'Master Organic, Inorganic, and Physical Chemistry for JEE Main and Advanced.', 'Complete chemistry preparation covering all three branches with special focus on reaction mechanisms, periodic properties, and chemical kinetics. Includes detailed notes and practice problems.', '/placeholder.svg', 7500, 9500, 10, 4.7, 4100, 970, 'Dr. Priya Mehta', 'PhD in Chemistry, 12 years teaching experience', '/placeholder.svg', 'JEE', true, 3, '["Organic reaction mechanisms", "Inorganic compound properties", "Physical chemistry calculations", "IUPAC nomenclature"]', '["250+ hours of lectures", "4000+ MCQs", "40 mock tests", "Study material PDFs"]'),
('JEE Mathematics Crash Course', 'jee-maths-crash', 'Intensive JEE Mathematics preparation', 'Fast-track mathematics course covering all JEE topics with focus on speed and accuracy.', 'Intensive mathematics course designed for last-minute preparation. Covers calculus, algebra, trigonometry, and coordinate geometry with emphasis on quick problem-solving.', '/placeholder.svg', 6000, 8000, 6, 4.6, 2890, 650, 'Mr. Sandeep Singh', 'Mathematics Olympiad gold medalist', '/placeholder.svg', 'JEE', true, 4, '["Quick calculation methods", "Formula shortcuts", "Pattern recognition", "Time-saving techniques"]', '["150+ hours of content", "2500+ problems", "30 topic tests", "Formula sheets"]'),
('JEE Main + Advanced Bundle', 'jee-main-advanced-bundle', 'Complete JEE preparation package', 'All-inclusive course for both JEE Main and Advanced examinations.', 'Comprehensive package covering everything needed for JEE Main and Advanced. Includes all subjects, unlimited practice tests, and personalized mentorship throughout your preparation journey.', '/placeholder.svg', 20000, 25000, 18, 4.9, 6780, 1890, 'Team of IIT Faculty', 'Multiple IIT professors and experts', '/placeholder.svg', 'JEE', true, 5, '["Complete syllabus coverage", "Main + Advanced preparation", "Personalized study plans", "Regular performance analysis"]', '["500+ hours of content", "10000+ questions", "100 mock tests", "Personal mentor", "Study material"]'),
('JEE Organic Chemistry Special', 'jee-organic-chemistry', 'Master Organic Chemistry for JEE', 'Specialized course focusing exclusively on Organic Chemistry concepts.', 'Deep dive into organic chemistry with focus on reaction mechanisms, name reactions, and stereochemistry. Perfect for students who want to excel in organic chemistry.', '/placeholder.svg', 5000, 6500, 5, 4.8, 2340, 560, 'Dr. Neha Gupta', 'Organic Chemistry specialist, 10 years experience', '/placeholder.svg', 'JEE', true, 6, '["Named reactions mastery", "Mechanism understanding", "Stereochemistry concepts", "Synthesis problems"]', '["100+ hours of lectures", "1500+ reactions", "20 topic tests", "Reaction flashcards"]'),
('JEE Physics Problem Solving', 'jee-physics-problems', 'Advanced physics problem solving', 'Learn to solve complex JEE physics problems with expert techniques.', 'Focused course on solving challenging physics problems. Covers all physics topics with emphasis on problem-solving strategies and conceptual clarity.', '/placeholder.svg', 5500, 7000, 6, 4.7, 1980, 470, 'Prof. Vikram Patel', 'IIT Bombay faculty, Physics researcher', '/placeholder.svg', 'JEE', true, 7, '["Problem-solving frameworks", "Conceptual approaches", "Multiple solution methods", "Exam strategies"]', '["120+ hours of content", "2000+ problems", "25 practice sets", "Video solutions"]'),
('JEE Inorganic Chemistry', 'jee-inorganic-chemistry', 'Complete Inorganic Chemistry course', 'Master Inorganic Chemistry with systematic approach.', 'Comprehensive inorganic chemistry course covering periodic table, chemical bonding, coordination compounds, and qualitative analysis with memory techniques.', '/placeholder.svg', 4500, 6000, 5, 4.6, 1670, 390, 'Dr. Kavita Reddy', 'Chemistry professor, IIT alumna', '/placeholder.svg', 'JEE', true, 8, '["Periodic trends", "Coordination chemistry", "Qualitative analysis", "Memory techniques"]', '["90+ hours of content", "1200+ MCQs", "15 topic tests", "Colorful notes"]'),
('JEE Calculus Masterclass', 'jee-calculus-master', 'Master Calculus for JEE', 'Deep understanding of differential and integral calculus.', 'Advanced calculus course covering limits, continuity, differentiation, integration, and applications with focus on JEE-style problems.', '/placeholder.svg', 5000, 6500, 5, 4.8, 2120, 510, 'Mr. Anil Kumar', 'Mathematics expert, 15 years experience', '/placeholder.svg', 'JEE', true, 9, '["Limit techniques", "Integration methods", "Application problems", "Curve sketching"]', '["100+ hours of lectures", "1800+ problems", "20 assignments", "Practice booklet"]'),
('JEE Revision Course', 'jee-revision-complete', 'Complete JEE revision package', 'Last-minute revision for all JEE topics.', 'Comprehensive revision course covering all important topics, formulas, and concepts with quick tips and exam strategies for final preparation.', '/placeholder.svg', 4000, 5500, 3, 4.7, 3450, 820, 'Expert Faculty Team', 'Team of experienced JEE trainers', '/placeholder.svg', 'JEE', true, 10, '["Quick revision techniques", "Important formulas", "Last-minute tips", "Exam strategies"]', '["80+ hours of content", "Summary notes", "Formula sheets", "Previous year solutions"]'),

-- NEET Courses (10)
('NEET Complete Course', 'neet-complete-course', 'Comprehensive NEET preparation', 'Complete course for NEET covering Physics, Chemistry, and Biology with expert guidance.', 'All-inclusive NEET preparation course with detailed coverage of all three subjects. Includes regular tests, doubt clearing sessions, and study materials designed as per latest NEET pattern.', '/placeholder.svg', 15000, 18000, 12, 4.9, 7230, 1650, 'Dr. Sunita Sharma', 'MBBS, MD with 12 years teaching experience', '/placeholder.svg', 'NEET', true, 1, '["NCERT-based learning", "NEET exam patterns", "Time management", "Answer writing techniques"]', '["400+ hours of content", "6000+ MCQs", "60 mock tests", "NCERT solutions", "Personal mentorship"]'),
('NEET Biology Mastery', 'neet-biology-master', 'Master Biology for NEET', 'Complete Biology preparation covering Botany and Zoology.', 'Comprehensive biology course covering all NCERT topics with additional diagrams, flowcharts, and memory techniques for better retention.', '/placeholder.svg', 9000, 11000, 10, 4.8, 5120, 1180, 'Dr. Ramesh Verma', 'PhD in Biology, NEET expert', '/placeholder.svg', 'NEET', true, 2, '["NCERT mastery", "Diagram techniques", "Memory methods", "Previous year analysis"]', '["250+ hours of lectures", "4000+ questions", "50 topic tests", "Diagram booklet"]'),
('NEET Physics Simplified', 'neet-physics-simple', 'Easy-to-understand NEET Physics', 'Simplified physics concepts for NEET with practical examples.', 'Physics course designed specifically for NEET aspirants with focus on NCERT and commonly asked questions. Includes simple explanations and numerical practice.', '/placeholder.svg', 6500, 8500, 8, 4.7, 3890, 890, 'Prof. Manoj Joshi', 'Physics professor, 15 years experience', '/placeholder.svg', 'NEET', true, 3, '["NCERT focus", "Simple explanations", "Numerical practice", "Quick formulas"]', '["180+ hours of content", "2500+ numericals", "35 tests", "Formula cards"]'),
('NEET Organic Chemistry', 'neet-organic-chem', 'Organic Chemistry for NEET', 'Master organic chemistry reactions and mechanisms.', 'Focused organic chemistry course covering all NEET topics with emphasis on name reactions, GOC, and biomolecules.', '/placeholder.svg', 5500, 7500, 6, 4.6, 2760, 640, 'Dr. Anjali Desai', 'Chemistry expert, NEET specialist', '/placeholder.svg', 'NEET', true, 4, '["Reaction mechanisms", "Biomolecules", "Polymers", "GOC concepts"]', '["120+ hours of lectures", "1800+ reactions", "25 tests", "Reaction notes"]'),
('NEET Human Physiology', 'neet-human-physiology', 'Complete Human Physiology course', 'Detailed coverage of human body systems.', 'In-depth human physiology course covering all body systems with diagrams, flowcharts, and clinical correlations for better understanding.', '/placeholder.svg', 6000, 8000, 7, 4.8, 3340, 780, 'Dr. Meera Iyer', 'MD with teaching expertise', '/placeholder.svg', 'NEET', true, 5, '["System-wise learning", "Clinical correlations", "Diagram mastery", "Physiology graphs"]', '["150+ hours of content", "2000+ MCQs", "30 topic tests", "Diagram atlas"]'),
('NEET Botany Complete', 'neet-botany-complete', 'Complete Plant Biology for NEET', 'Comprehensive botany covering all NEET topics.', 'Full botany course from plant morphology to ecology with special focus on diagrams and classification that are frequently asked in NEET.', '/placeholder.svg', 5000, 6500, 6, 4.7, 2450, 570, 'Dr. Pooja Nair', 'Botany PhD, NEET trainer', '/placeholder.svg', 'NEET', true, 6, '["Plant diversity", "Morphology diagrams", "Plant physiology", "Ecology concepts"]', '["130+ hours of lectures", "1500+ questions", "28 tests", "Plant diagrams"]'),
('NEET Zoology Mastery', 'neet-zoology-master', 'Master Animal Biology for NEET', 'Complete zoology preparation for NEET exam.', 'Comprehensive zoology course covering animal diversity, human physiology, and genetics with focus on NCERT and previous year questions.', '/placeholder.svg', 5500, 7000, 6, 4.8, 2890, 670, 'Dr. Rakesh Pillai', 'Zoology expert, 10 years experience', '/placeholder.svg', 'NEET', true, 7, '["Animal classification", "Human systems", "Genetics basics", "Evolution concepts"]', '["140+ hours of content", "1700+ MCQs", "30 tests", "Animal diagrams"]'),
('NEET Genetics & Evolution', 'neet-genetics-evolution', 'Genetics and Evolution for NEET', 'Master genetics and evolution concepts.', 'Specialized course on genetics, molecular biology, and evolution with focus on problem-solving and diagrammatic questions.', '/placeholder.svg', 4500, 6000, 5, 4.6, 1890, 440, 'Dr. Suresh Menon', 'Genetics specialist', '/placeholder.svg', 'NEET', true, 8, '["Mendelian genetics", "Molecular biology", "DNA technology", "Evolution theories"]', '["100+ hours of lectures", "1200+ questions", "20 tests", "Gene diagrams"]'),
('NEET Chemistry Complete', 'neet-chemistry-full', 'Complete Chemistry for NEET', 'All chemistry topics for NEET preparation.', 'Comprehensive chemistry course covering physical, organic, and inorganic chemistry as per NEET syllabus with NCERT focus.', '/placeholder.svg', 8000, 10000, 9, 4.7, 4120, 950, 'Dr. Vinod Rao', 'Chemistry professor, NEET expert', '/placeholder.svg', 'NEET', true, 9, '["NCERT chemistry", "All three branches", "Numerical problems", "Chemical equations"]', '["220+ hours of content", "3500+ MCQs", "45 mock tests", "Reaction booklet"]'),
('NEET Last Minute Revision', 'neet-last-revision', 'Quick revision for NEET', 'Fast-track revision of all NEET topics.', 'Intensive revision course covering all important topics, diagrams, and formulas with quick tips for last-minute preparation before NEET exam.', '/placeholder.svg', 3500, 5000, 2, 4.8, 4560, 1050, 'Team of NEET Experts', 'Experienced NEET faculty', '/placeholder.svg', 'NEET', true, 10, '["Quick topic revision", "Important diagrams", "Formula sheets", "Exam tips"]', '["60+ hours of content", "Summary notes", "Diagram compilation", "Previous papers"]'),

-- Board Exam Courses (5)
('Class 12 Physics CBSE', 'class-12-physics-cbse', 'Complete Class 12 Physics', 'CBSE Class 12 Physics with board exam focus.', 'Complete CBSE Class 12 Physics course covering all chapters with board exam pattern, numerical practice, and theory explanations.', '/placeholder.svg', 4000, 5500, 10, 4.7, 3120, 720, 'Mr. Deepak Saxena', 'CBSE school teacher, 18 years experience', '/placeholder.svg', 'Board Exams', true, 1, '["NCERT solutions", "Board exam patterns", "Numerical mastery", "Derivations"]', '["150+ hours of lectures", "2000+ numericals", "Board-style tests", "Previous year papers"]'),
('Class 12 Chemistry CBSE', 'class-12-chemistry-cbse', 'Complete Class 12 Chemistry', 'CBSE Class 12 Chemistry course.', 'Full CBSE Class 12 Chemistry preparation with focus on both theory and practicals, covering all three branches as per board syllabus.', '/placeholder.svg', 4000, 5500, 10, 4.6, 2890, 670, 'Mrs. Rekha Agarwal', 'CBSE Chemistry teacher, 15 years', '/placeholder.svg', 'Board Exams', true, 2, '["NCERT coverage", "Practical concepts", "Equation balancing", "Board answers"]', '["140+ hours of content", "1800+ questions", "Practical notes", "Sample papers"]'),
('Class 12 Biology CBSE', 'class-12-biology-cbse', 'Complete Class 12 Biology', 'CBSE Class 12 Biology preparation.', 'Comprehensive CBSE Class 12 Biology course covering botany and zoology with diagrams, flowcharts, and board exam strategies.', '/placeholder.svg', 4500, 6000, 10, 4.8, 3450, 800, 'Dr. Shalini Kapoor', 'CBSE Biology expert, 12 years', '/placeholder.svg', 'Board Exams', true, 3, '["NCERT diagrams", "Board writing tips", "Long answers", "Practical biology"]', '["160+ hours of lectures", "2200+ MCQs", "Diagram practice", "Board papers"]'),
('Class 12 Mathematics CBSE', 'class-12-maths-cbse', 'Complete Class 12 Mathematics', 'CBSE Class 12 Maths preparation.', 'Full CBSE Class 12 Mathematics course covering calculus, algebra, probability, and vectors with step-by-step problem solving.', '/placeholder.svg', 4500, 6000, 10, 4.7, 4230, 980, 'Mr. Sunil Gupta', 'Mathematics HOD, CBSE school', '/placeholder.svg', 'Board Exams', true, 4, '["Complete syllabus", "Step-by-step solutions", "Board exam tips", "Important questions"]', '["170+ hours of content", "2500+ problems", "Chapter tests", "Sample papers"]'),
('Class 11 PCM Foundation', 'class-11-pcm-foundation', 'Class 11 Science Foundation', 'Strong foundation for Class 11 PCM.', 'Foundation course for Class 11 students covering Physics, Chemistry, and Mathematics with focus on building strong conceptual base.', '/placeholder.svg', 8000, 10000, 10, 4.6, 2340, 540, 'Expert Faculty Team', 'Team of CBSE teachers', '/placeholder.svg', 'Board Exams', true, 5, '["Concept building", "NCERT mastery", "Foundation strength", "Regular practice"]', '["300+ hours of content", "4000+ questions", "Subject-wise tests", "Study materials"]'),

-- Integrated Courses (5)
('JEE + Board Integrated Class 12', 'jee-board-integrated-12', 'JEE and Board together for Class 12', 'Prepare for both JEE and Board exams simultaneously.', 'Unique integrated course that prepares students for both JEE and CBSE Board exams together, covering all topics at both levels.', '/placeholder.svg', 18000, 22000, 12, 4.9, 4560, 1050, 'Integrated Faculty Team', 'JEE and Board experts', '/placeholder.svg', 'Integrated', true, 1, '["Dual preparation", "JEE + Board focus", "Time optimization", "Complete coverage"]', '["450+ hours of content", "8000+ questions", "JEE + Board tests", "Dual study material"]'),
('NEET + Board Integrated Class 12', 'neet-board-integrated-12', 'NEET and Board together', 'Simultaneous preparation for NEET and Board.', 'Integrated course for Class 12 students preparing for both NEET and CBSE Board exams with optimized study plan and time management.', '/placeholder.svg', 18000, 22000, 12, 4.8, 5120, 1180, 'Medical Expert Team', 'NEET and CBSE specialists', '/placeholder.svg', 'Integrated', true, 2, '["NEET + Board combo", "Efficient preparation", "NCERT mastery", "Exam strategies"]', '["480+ hours of lectures", "9000+ MCQs", "Dual mock tests", "Complete materials"]'),
('Foundation Course Class 9-10', 'foundation-9-10', 'Early foundation for competitive exams', 'Build strong foundation for future competitive exams.', 'Foundation course for Class 9-10 students interested in preparing early for JEE/NEET while maintaining focus on board exams.', '/placeholder.svg', 12000, 15000, 24, 4.7, 3240, 750, 'Foundation Experts', 'Experienced foundation trainers', '/placeholder.svg', 'Integrated', true, 3, '["Early preparation", "Concept clarity", "Board + competitive", "Long-term planning"]', '["600+ hours of content", "10000+ questions", "Regular assessments", "Progress tracking"]'),
('Olympiad + JEE Preparation', 'olympiad-jee-prep', 'Olympiad and JEE together', 'Prepare for Physics/Chemistry/Math Olympiads and JEE.', 'Advanced course combining Olympiad-level problem solving with JEE preparation for highly motivated students.', '/placeholder.svg', 16000, 20000, 18, 4.9, 1890, 430, 'Olympiad Champions', 'Olympiad medalists and IIT faculty', '/placeholder.svg', 'Integrated', true, 4, '["Advanced concepts", "Olympiad strategies", "JEE preparation", "Challenge problems"]', '["500+ hours of content", "5000+ problems", "Olympiad resources", "JEE materials"]'),
('Complete Science Package 11-12', 'complete-science-11-12', 'Two-year complete science course', 'Full two-year preparation for Class 11-12.', 'Comprehensive two-year package covering all science subjects for Class 11-12 with both board and competitive exam preparation.', '/placeholder.svg', 25000, 30000, 24, 4.8, 5670, 1300, 'Complete Faculty Team', 'All-subject expert team', '/placeholder.svg', 'Integrated', true, 5, '["Two-year planning", "All subjects", "Board + competitive", "Complete guidance"]', '["800+ hours of content", "15000+ questions", "100+ mock tests", "Complete study kit"]');